### PR TITLE
Remove unofficial MusicXML test suite

### PR DESCRIPTION
**Pull request by rettinghaus**
* remove LilyPond's unofficial MusicXML test suite (now available at:https://github.com/cuthbertLab/musicxmlTestSuite)
* add warning about outdated stylesheets (as discussed on last ODD thursday)

### CODE REVIEW

**Comment by rettinghaus** [comment]
@kepper what about this one?

**Comment by kepper** [comment]
@rettinghaus, could you please add a little more background? I know a lot of work went into Verovio's MusicXML import recently, but last time I did such conversions, the XSLT was still a viable option, even though one may need to do another conversion to get it into 4.0 afterwards. Therefore, I'm not sure if the warning is really necessary or appropriate – could be, I just don't know. Regarding the removal of the test files, I wonder if there is a reference to the other repo already? Is this whole thing something we may want to discuss next week at the developer workshop?

**Comment by rettinghaus** [comment]
@kepper This is what we agreed on back in spring. We could change the content of the warning, but I still think we should indicate the "outdated" output in some way.

**Comment by musicEnfanthen** [comment]
I am wondering if we can move this forward. Would it be possible to separate the removal of the test suite from the addition of the "warning" in another PR, @rettinghaus ?

To understand the consequences better, could you please give a short reminder what the test suite was used for, where it was referenced from the XSLT files, and how this is supposed to work after the test suite would be removed?

For the "outdated" warning: I would prefer to indicate in the README that one would need to use another XSLT (https://github.com/music-encoding/encoding-tools/tree/main/mei30To40) to go from mei3.0 to mei4.0, instead of saying that these scripts are outdated, since they actually do what their name says: transcoding musicxml to mei v3 (or 2.3, etc.)

@rettinghaus @kepper What do you think?

**Comment by rettinghaus** [comment]
@musicEnfanthen The _MusicXML test suite_ was probably something left from the original development of the XSLT, but is nowhere referenced from anywhere within the tools. As I stated above, these is also not official test files for MusicXML but came as part of LilyPond for their MusicXML import script. The updated and extended _MusicXML Test Suite_ is now available at https://github.com/cuthbertLab/musicxmlTestSuite (see readme there). 

I removed the warning here and will add another PR.

**Pull request merged**
